# -*- coding: utf-8 -*-
"""Write assets/js/build.js - the date and revision the footer shows.

Run before every deploy:  python tools/stamp.py

The footer says "last updated" because a visitor looking at a shop that has been
open since 1967 wants to know the website is still tended. A hand-typed date in
the HTML answers that question wrongly within a week, so it is generated here
from the actual commit, and falls back to the file dates if git is not there.
"""
import json
import os
import subprocess
import time

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'assets', 'js', 'build.js')


def git(*args):
    try:
        return subprocess.check_output(['git'] + list(args), cwd=ROOT,
                                       stderr=subprocess.DEVNULL).decode().strip()
    except Exception:
        return ''


def newest_source():
    """Latest mtime across the files a visitor would call 'the site'."""
    newest = 0
    for sub in ('assets/js', 'assets/css', ''):
        d = os.path.join(ROOT, sub)
        for name in os.listdir(d):
            p = os.path.join(d, name)
            if os.path.isfile(p) and name.rsplit('.', 1)[-1] in ('js', 'css', 'html'):
                newest = max(newest, os.path.getmtime(p))
    return newest or time.time()


def main():
    iso = git('log', '-1', '--format=%cI')
    rev = git('rev-parse', '--short', 'HEAD')
    if not iso:
        iso = time.strftime('%Y-%m-%dT%H:%M:%S', time.localtime(newest_source()))

    payload = {'date': iso, 'rev': rev or None,
               'stamped': time.strftime('%Y-%m-%dT%H:%M:%S')}

    body = (
        '/* Generated by tools/stamp.py - do not edit.\n'
        '   The footer reads this to print "last updated". Regenerate before every\n'
        '   deploy or the date on the live site is the date of the deploy before. */\n'
        'window.SH_BUILD = %s;\n' % json.dumps(payload, indent=2)
    )
    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write(body)
    print('wrote', os.path.relpath(OUT, ROOT), '->', iso, rev or '(no git)')


if __name__ == '__main__':
    main()
